### ISSUE TITLE
[BUG] MIDI Controller Pitch/Mod Wheel Detection

### ISSUE THREAD

**Issue by maximilian-hub** [yokemura/Magical8bitPlug2#10]
**Describe the bug**
This bug relates to realtime performance with a MIDI controller.
Changes to the wheels will not take effect unless they are moved after a note is already playing.

**To Reproduce**
1. Open an Magic8Bit track in any DAW (I tested Studio One, Reaper64, and Garageband)
2. Set the pitch wheel to its lowest value (by default this should result in a pitch bend of -2)
3. Play a C
4. Hear that the note that plays is a C, instead of a Bb

(5.) While still holding the note, return the pitch wheel to neutral position
(6.) Hear the pitch update as soon as the wheel moves

**Expected behavior**
I expected the plugin to detect the position of the wheel *before* the note was played.

**Screenshots**
This is what I'm playing in both audio samples. You can see for the second note, the pitch wheel is depressed before the note is played:
<img width="1117" alt="Screen Shot 2020-09-13 at 12 36 59 PM" src="https://user-images.githubusercontent.com/61955124/93025268-1b60a300-f5c2-11ea-8f63-e65bd5c40312.png">

**Audio**
[What I hear with Magic8Bit](https://voca.ro/1o10JLEfyuYD) 
[What I hear with other VSTs](https://vocaroo.com/12xHBVPHd9NK)

**Your environment (please complete the following information):**
 - OS: macOS 10.13
 - Host DAW and version: Garageband 10.1.1, Reaper v6.13/64, Studio One 3.5.6.46910 OSX x64
 - Version of Magical 8bit Plug 2: not sure but I just downloaded it yesterday (sept. 13, 2020)
 - Plugin format of Magical 8bit Plug you used: AU, VST1, and VST3

**Additional context**
It's not a big deal for the sample I gave, as you could just play the Bb and bend it up to a C. But there are a lot of other applications in performing where I rely on this! The same problem applies to the mod wheel.

**Comment by yokemura** [comment]
Noted.

Probably It's not taking the initial pitch/mod value passed with the note on event.
I'll check it out.
