### ISSUE TITLE
Vibrato issue

### ISSUE THREAD

**Issue by flubber2077** [yokemura/Magical8bitPlug2#27]
**Describe the bug**
Rate control of vibrato is reversed from expected behavior (vibrato gets slower as control is increased towards 1)

**To Reproduce**
On default settings, turning depth up until modulation is audible, sweeping the rate down increases the speed and turning it up decreases.

**Expected behavior**
As rate is increased, the rate of the vibrato increases in hertz.

**Your environment (please complete the following information):**
 - OS: Windows 10
 - Ableton 11
 - Current version, built this morning
 - VST3

**Comment by yokemura** [comment]
Thanks for your report and sorry for my slow response.
You are correct in a sense that the label "rate" and the actual behavior don't match.

But my intended behavior is that the slider sets the cycle length, so what's wrong is the label.
It should say "cycle length" or "time".

**Comment by flubber2077** [comment]
I like that just as much! Thanks for your time.
