### ISSUE TITLE
Reaper

### ISSUE THREAD

**Issue by spirius44** [yokemura/Magical8bitPlug2#6]
Hi, Magical 8 bit Plug-in2 version not working with Reaper but the older (Plug-in 1 ) yes. Can you fix it please? It's for my students :)

**Comment by yokemura** [comment]
I cannot fix it without any detail provided

**Comment by yokemura** [comment]
I've created issue templates.
Please reopen the issue and follow the format to detail your issue.

**Comment by spirius44** [comment]
Okay, but what’s the format?
I used the last dell and vst3 files and Reaper not recognize the VST during the scan.

On my Mac it’s okay but not on Windows 10 (last update too). However your first Magical 8 bit (plug in 1) works.

**Comment by yokemura** [comment]
Sorry, my words weren't enough. 

Please open a new issue with the `New issue` button on the top right corner of this page and you'll see the screen to choose the issue templates. Then choose `Bug report` to see the format with the list of information you should provide as a bug report.
